import type { CSSProperties } from 'react';

const styles = {
  container: {
    backgroundColor: '#ffffff',
    position: 'relative',
    borderRadius: '30px',
    width: '100%',
    height: '100%',
  } as CSSProperties,
  innerContainer: {
    position: 'relative',
    width: '100%',
    height: '100%',
  } as CSSProperties,
  contentBox: {
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    gap: '24px',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    overflow: 'clip',
    padding: '40px',
    position: 'relative',
    width: '100%',
    height: '100%',
    borderRadius: '30px',
    border: '1px solid #D0D5DD',
  } as CSSProperties,
  sectionContainer: {
    position: 'relative',
    flexShrink: 0,
    width: '100%',
  } as CSSProperties,
  sectionBox: {
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    padding: 0,
    position: 'relative',
    width: '100%',
  } as CSSProperties,
  sectionTitle: {
    display: 'flex',
    flexDirection: 'column',
    fontFamily: "'Suisse Intl:Regular', sans-serif",
    fontWeight: 'normal',
    justifyContent: 'center',
    lineHeight: 0,
    minWidth: '100%',
    fontStyle: 'normal',
    position: 'relative',
    flexShrink: 0,
    color: '#000000',
    fontSize: '24px',
    textAlign: 'left',
    letterSpacing: '-0.72px',
  } as CSSProperties,
  sectionTitleText: {
    display: 'block',
    lineHeight: 1.3,
    fontFamily: 'Suisse Intl',
    fontSize: '24px',
    margin: 0,
  } as CSSProperties,
  dragDropArea: (dragActive: boolean) =>
    ({
      position: 'relative',
      flexShrink: 0,
      width: '100%',
      backgroundColor: dragActive ? '#f5f5ff' : 'transparent',
      height: '200px',
      borderRadius: '16px',
      border: '1px dashed #8f8ff3',
    } as CSSProperties),
  dragDropContent: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    width: '100%',
    height: '100%',
  } as CSSProperties,
  dragDropBox: {
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
    height: '200px',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '12px',
    position: 'relative',
    width: '100%',
  } as CSSProperties,
  uploadText: {
    fontFamily: "'Suisse Intl:Regular', sans-serif",
    fontWeight: 'normal',
    lineHeight: 0,
    fontStyle: 'normal',
    position: 'relative',
    flexShrink: 0,
    color: '#3d3de9',
    fontSize: '14px',
    textAlign: 'center',
    whiteSpace: 'nowrap',
  } as CSSProperties,
  uploadTextP: {
    display: 'block',
    lineHeight: '22px',
    whiteSpace: 'pre',
    margin: 0,
  } as CSSProperties,
  uploadButton: {
    position: 'relative',
    borderRadius: '16px',
    boxShadow: '0px 1px 2px 0px rgba(20,21,26,0.05)',
    flexShrink: 0,
    backgroundColor: '#0000ff',
    width: '100%',
    maxWidth: 220,
    cursor: 'pointer',
  } as CSSProperties,
  uploadButtonContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'clip',
    position: 'relative',
    width: '100%',
    height: '100%',
  } as CSSProperties,
  uploadButtonBox: {
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'row',
    gap: '4px',
    alignItems: 'center',
    justifyContent: 'center',
    paddingLeft: '16px',
    paddingRight: '16px',
    paddingTop: '18px',
    paddingBottom: '18px',
    position: 'relative',
    width: 'fit-content',
  } as CSSProperties,
  uploadButtonText: {
    fontFamily: "'Suisse Intl:Book', sans-serif",
    fontWeight: 450,
    lineHeight: 0,
    fontStyle: 'normal',
    position: 'relative',
    flexShrink: 0,
    color: '#ffffff',
    fontSize: '20px',
    textAlign: 'center',
    whiteSpace: 'nowrap',
    letterSpacing: '-0.02em',
  } as CSSProperties,
  uploadButtonTextP: {
    display: 'block',
    lineHeight: '24px',
    whiteSpace: 'pre',
    margin: 0,
  } as CSSProperties,
  fileTypeText: {
    fontFamily: "'Suisse Intl:Regular', sans-serif",
    fontWeight: 'normal',
    lineHeight: 0,
    fontStyle: 'normal',
    position: 'relative',
    flexShrink: 0,
    color: '#3d3de9',
    fontSize: '14px',
    textAlign: 'center',
    whiteSpace: 'nowrap',
  } as CSSProperties,
  fileTypeTextP: {
    display: 'block',
    lineHeight: '22px',
    whiteSpace: 'pre',
    margin: 0,
  } as CSSProperties,
  linkInput: {
    backgroundColor: '#ffffff',
    height: '54px',
    position: 'relative',
    borderRadius: '12px',
    flexShrink: 0,
    width: '100%',
  } as CSSProperties,
  linkInputContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'clip',
    position: 'relative',
    width: '100%',
    height: '100%',
  } as CSSProperties,
  linkInputBox: {
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'row',
    gap: '8px',
    height: '54px',
    alignItems: 'center',
    justifyContent: 'flex-start',
    paddingLeft: '14px',
    paddingRight: '14px',
    paddingTop: '8px',
    paddingBottom: '8px',
    position: 'relative',
    width: '100%',
  } as CSSProperties,
  linkInputField: {
    flexBasis: 0,
    fontFamily: "'Suisse Intl:Regular', sans-serif",
    fontWeight: 'normal',
    flexGrow: 1,
    lineHeight: 0,
    minHeight: '1px',
    minWidth: '1px',
    fontStyle: 'normal',
    position: 'relative',
    flexShrink: 0,
    fontSize: '16px',
    textAlign: 'left',
    border: 'none',
    outline: 'none',
  } as CSSProperties,
  linkInputBorder: {
    position: 'absolute',
    border: '1px solid #d0d5dd',
    borderStyle: 'solid',
    inset: 0,
    pointerEvents: 'none',
    borderRadius: '12px',
  } as CSSProperties,
  languageOptionsContainer: {
    position: 'relative',
    flexShrink: 0,
    width: '100%',
  } as CSSProperties,
  languageOptionsBox: {
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'row',
    gap: '4px',
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    padding: 0,
    position: 'relative',
    width: '100%',
    flexWrap: 'wrap',
  } as CSSProperties,
  languageOption: (isSelected: boolean) =>
    ({
      flexBasis: 0,
      backgroundColor: '#ffffff',
      flexGrow: 1,
      height: '44px',
      minHeight: '1px',
      minWidth: '1px',
      width: 140,
      position: 'relative',
      borderRadius: '59px',
      flexShrink: 0,
      cursor: 'pointer',
      border: isSelected ? '1px solid  #8F8FF3' : '1px solid #d0d5dd',
    } as CSSProperties),
  languageOptionContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    width: '100%',
    height: '100%',
  } as CSSProperties,
  languageOptionBox: {
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'row',
    gap: '6px',
    height: '44px',
    alignItems: 'center',
    justifyContent: 'center',
    paddingLeft: '20px',
    paddingRight: '20px',
    paddingTop: '12px',
    paddingBottom: '12px',
    position: 'relative',
    width: '100%',
  } as CSSProperties,
  languageText: {
    fontFamily: "'Suisse Intl:Regular', sans-serif",
    fontWeight: 'normal',
    lineHeight: 0,
    fontStyle: 'normal',
    position: 'relative',
    flexShrink: 0,
    color: '#101828',
    fontSize: '16px',
    textAlign: 'left',
    whiteSpace: 'nowrap',
    letterSpacing: '-0.5px',
  } as CSSProperties,
  languageTextP: {
    display: 'block',
    lineHeight: '22px',
    whiteSpace: 'pre',
  } as CSSProperties,
  toneSelector: {
    position: 'relative',
    flexShrink: 0,
    width: '100%',
    backgroundColor: '#ffffff',
    height: '44px',
    borderRadius: '59px',
    cursor: 'pointer',
  } as CSSProperties,
  toneSelectorBorder: {
    position: 'absolute',
    border: '1px solid #d0d5dd',
    borderStyle: 'solid',
    inset: 0,
    pointerEvents: 'none',
    borderRadius: '59px',
  } as CSSProperties,
  toneSelectorContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    position: 'relative',
    width: '100%',
    height: '100%',
  } as CSSProperties,
  toneSelectorBox: {
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'row',
    gap: '6px',
    height: '44px',
    alignItems: 'center',
    justifyContent: 'center',
    paddingLeft: '20px',
    paddingRight: '20px',
    paddingTop: '12px',
    paddingBottom: '12px',
    position: 'relative',
    width: '100%',
  } as CSSProperties,
  toneText: {
    fontFamily: "'Suisse Intl:Regular', sans-serif",
    fontWeight: 'normal',
    lineHeight: 0,
    fontStyle: 'normal',
    position: 'relative',
    flexShrink: 0,
    color: '#101828',
    fontSize: '16px',
    textAlign: 'left',
    whiteSpace: 'nowrap',
    letterSpacing: '-0.5px',
  } as CSSProperties,
  toneTextP: {
    display: 'block',
    lineHeight: '22px',
    whiteSpace: 'pre',
  } as CSSProperties,
  iconContainer: {
    position: 'relative',
    flexShrink: 0,
    width: '16px',
    height: '16px',
  } as CSSProperties,
  submitButton: (isDisabled: boolean) =>
    ({
      position: 'relative',
      borderRadius: '16px',
      boxShadow: '0px 1px 2px 0px rgba(20,21,26,0.05)',
      flexShrink: 0,
      width: '100%',
      backgroundColor: isDisabled ? '#d1d1fa' : '#0000ff',
      cursor: isDisabled ? 'default' : 'pointer',
    } as CSSProperties),
  submitButtonContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'clip',
    position: 'relative',
    width: '100%',
    height: '100%',
  } as CSSProperties,
  submitButtonBox: {
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'row',
    gap: '4px',
    alignItems: 'center',
    justifyContent: 'center',
    paddingLeft: '16px',
    paddingRight: '16px',
    paddingTop: '18px',
    paddingBottom: '18px',
    position: 'relative',
    width: '100%',
  } as CSSProperties,
  submitButtonText: {
    fontFamily: "'Suisse Intl:Book', sans-serif",
    fontWeight: 450,
    lineHeight: 0,
    fontStyle: 'normal',
    position: 'relative',
    flexShrink: 0,
    color: '#ffffff',
    fontSize: '20px',
    textAlign: 'center',
    whiteSpace: 'nowrap',
    letterSpacing: '-0.4px',
  } as CSSProperties,
  submitButtonTextP: {
    display: 'block',
    lineHeight: '24px',
    whiteSpace: 'pre',
    margin: 0,
  } as CSSProperties,
  flagContainer: {
    position: 'relative',
    flexShrink: 0,
    width: '24px',
    height: '24px',
  } as CSSProperties,
  flagBox: {
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'clip',
    padding: 0,
    position: 'relative',
    width: '24px',
    height: '24px',
  } as CSSProperties,
  flagSize: {
    height: '16px',
    position: 'relative',
    flexShrink: 0,
    width: '22px',
  } as CSSProperties,
  flagSvg: {
    display: 'block',
    width: '100%',
    height: '100%',
  } as CSSProperties,
  englishFlagContainer: {
    overflow: 'clip',
    position: 'relative',
    flexShrink: 0,
    width: '24px',
    height: '24px',
  } as CSSProperties,
  englishFlagInner: {
    position: 'absolute',
    height: '16px',
    left: '50%',
    top: '50%',
    transform: 'translate(-50%, -50%)',
    width: '22px',
  } as CSSProperties,
  // Uploaded file styles
  uploadedFileContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '16px',
    backgroundColor: '#ffffff',
    border: '1px solid #D0D5DD',
    borderRadius: '16px',
    position: 'relative',
    flexShrink: 0,
    width: '100%',
    boxSizing: 'border-box',
  } as CSSProperties,
  uploadedFileContent: {
    display: 'flex',
    alignItems: 'center',
    gap: '12px',
    flex: 1,
  } as CSSProperties,
  uploadedFileIcon: {
    width: '40px',
    height: '40px',
    backgroundColor: '#3d3de9',
    borderRadius: '8px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#ffffff',
    fontSize: '18px',
    fontWeight: 'bold',
    flexShrink: 0,
  } as CSSProperties,
  uploadedFileInfo: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
    minWidth: 0,
  } as CSSProperties,
  uploadedFileName: {
    fontFamily: "'Suisse Intl:Regular', sans-serif",

    fontSize: '16px',
    lineHeight: '22px',
    fontWeight: 500,
    color: '#101828',
    margin: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  } as CSSProperties,
  uploadedFileSize: {
    fontFamily: "'Suisse Intl:Regular', sans-serif",
    fontWeight: 'normal',
    fontSize: '14px',
    lineHeight: '20px',
    color: '#667085',
    margin: 0,
  } as CSSProperties,
  uploadedFileRemove: {
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: '8px',
    color: '#667085',
    fontSize: '16px',
    borderRadius: '8px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: '32px',
    height: '32px',
    flexShrink: 0,
    transition: 'background-color 0.15s ease',
  } as CSSProperties,
};

export default styles;
