import type { CSSProperties } from 'react';

export const styles = {
  container: {
    display: 'flex',
    alignItems: 'center',
    overflow: 'hidden',
    width: '100%',
    position: 'relative',
  },
  scrollingWrapper: {
    overflow: 'hidden',
    width: '100%',
  },
  scrollingContent: {
    display: 'flex',
    gap: 10,
    animation: 'scroll 20s linear infinite',
    width: 'fit-content',
  },
  featureContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    width: 440,
    height: 240,
    padding: '20px 0',
    borderRadius: 20,
    background: '#F9FAFB',
    flexShrink: 0,
    justifyContent: 'center',
  },
  featureContent: {
    display: 'flex',
    gap: 5,
    alignItems: 'center',
    width: '100%',
    justifyContent: 'center',
  },
  featureContentText: {
    fontStyle: 'normal',
    fontFamily: 'Suisse Intl',
    fontWeight: 450,
    lineHeight: '95%',
  },
  featureB: {
    borderRadius: '8.357px',
    border: '0.522px solid  #EAECF0',
    background: '#FFF',
    flexDirection: 'column',
    display: 'flex',
  },
  featureBContent: {
    padding: '16px 8px',
    flexDirection: 'column',
    justifyContent: 'flex-end',
    alignItems: 'flex-start',
    gap: '8px',
  },
  featureBContentTitle: {
    fontFamily: 'Suisse Intl',
    fontSize: '10.024px',
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '95%',
    letterSpacing: '-0.301px',
    color: '#000',
    margin: 0,
  },
  featureBContentText: {
    fontFamily: 'Suisse Intl',
    fontSize: '8.353px',
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '95%',
    letterSpacing: '-0.418px',
    color: '#000',
    margin: 0,
  },
} satisfies Record<string, CSSProperties>;
